### PR TITLE
upgrade schemars to 0.8

### PR DESCRIPTION
**Pull request by mikeyhew**

### CODE REVIEW

**Comment by davepacheco** [comment]
@ahl any objection here?  Here's the change log: https://github.com/GREsau/schemars/blob/master/CHANGELOG.md

There are a bunch of breaking changes here but CI passed on all platforms so I believe that means they don't affect us.

**Comment by davepacheco** [comment]
(thanks @mikeyhew!)

**Comment by ahl** [comment]
No objection! If CI is happy, I'm happy!

**Comment by davepacheco** [comment]
Thanks again.

**Pull request merged**
